@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdhYzlkZTNiZjg4ZTM3NWY1OTQ1NzciLCJpYXQiOjE2MzU0MzgzMTIsImV4cCI6MTYzNjA0MzExMn0.KH_LhkeraTLrHj3EvvoT25fuWKcwje0PkOSU6uYhTSs
@reset_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdhYzlkZTNiZjg4ZTM3NWY1OTQ1NzciLCJpYXQiOjE2MzU0NDA5MDAsImV4cCI6MTYzNTQ0MTAyMH0.xUCaVfrxqZGqFtMyC4h89cwqC1L8LKLrun1q7eeXilo

### Register
POST http://127.0.0.1:5200/api/register HTTP/1.1
content-type: application/json

{
    "password":"111998tsc",
    "confirm_password":"111998tsc",
    "email":"souksavansh.personal@gmail.com",
    "username":"souksavanh"
}

### LOGIN
POST http://127.0.0.1:5200/api/login HTTP/1.1
content-type: application/json

{
    "password":"123123123",
    "username":"souksavanh.personal@gmail.com"
}


### PROFILE
GET http://127.0.0.1:5200/api/me
Authorization: {{token}}


### Send OTP
POST http://127.0.0.1:5200/api/send-otp
content-type: application/json

{
    "email":"souksavanh.personal@gmail.com"
}


### Verify OTP
POST http://127.0.0.1:5200/api/verify-otp
content-type: application/json
Authorization: {{reset_token}}

{
    "otp_code":"392939"
}

### Verify OTP
POST http://127.0.0.1:5200/api/reset-password
content-type: application/json
Authorization: {{reset_token}}

{
    "password":"123123123"
}



### Response Code Error
GET http://127.0.0.1:5200/api/user/error-code
